flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import render_template, request, Blueprint, url_for, redirect
from flaskblog.models import Post
from flask_login import login_required

main = Blueprint('main', __name__)


@main.route("/")
def achintyajha():
    return render_template('achintyajha.html', title='Home')


@main.route("/home")
def home():
    return render_template('home.html', title='Home')


@main.route("/blog")
def blog():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('blog.html', posts=posts, title='Blog')


@main.route("/highschool")
def highschool():
	return render_template('hs.html', title='High School')


@main.route("/FAQs")
def faq():
	return render_template('faqs.html', title='FAQs')


@main.route("/Programming")
def programming():
	return render_template('programming.html', title='Python and Stuff')


@main.route("/resume")
def resume():
	return redirect(url_for('static', filename="resources/Achintya's Resume.pdf"))

	

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    if current_user.username == 'Achintya':
        form = PostForm()
        if form.validate_on_submit():
            post = Post(title=form.title.data, content=form.content.data, author=current_user)
            db.session.add(post)
            db.session.commit()
            flash('Your post has been created!', 'success')
            return redirect(url_for('main.blog'))
        return render_template('create_post.html', title='New Post',
                               form=form, legend='New Post')

    else:
        abort(403)


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.blog'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        flash('Do check in the spam section of your email as well.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/achintyajha.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Achintya Jha</title>

  <link rel="stylesheet" type="text/css" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='landing.css') }}">

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Jost:ital@1&display=swap" rel="stylesheet">

  <link href="//db.onlinewebfonts.com/c/046e1373d00f74810d24a0f19010b1cc?family=BergenSans-Regular" rel="stylesheet" type="text/css"/>

  <link rel = "shortcut icon" href="static/img/title-icon-final.jpeg">

  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-TC477NL');</script>
  <!-- End Google Tag Manager -->

</head>


<body>

  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TC477NL"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->

  <section style="background-image: url('static/img/code-min.jpg'); background-size: cover;">

    <!-- <div class="circle"></div> -->
    <header>
      <span class="brand" style="background-color: yellow;">Achintya Jha</span>
      <!-- <div class="toggle" onclick="toggleMenu()"></div>
      <ul class="navigation">
        <li><a href="#">Home</a></li>
        <li><a href="#">Menu</a></li>
        <li><a href="#">New</a></li>
        <li><a href="#">Contact</a></li>
      </ul> -->
    </header>

        <div class="content-section">
          <h2>Hey, I am Achintya!</h2>
          <p>
            I am a highschool senior at Ahlcon International School, and I absolutely love to code. I am interested in Machine Learning and Natural Language Processing. I have been using
            python for more than three years now and I use it for almost everything. This website
            includes my portfolio and a list of all the projects I have made throughout high school. 
            <br>
            Check out the rest of the website down below, and don't forget to check out my blog! 
          </p>
          <a href="{{ url_for('main.home') }}">Explore</a>
        </div>

      <ul class="sci">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  
        <li><a href="https://in.linkedin.com/" class="fa fa-linkedin fa-2x"></a></li>
        <li><a href="https://github.com/achintya5" class="fa fa-github fa-2x"></a></li>
        <li><a href="mailto:achintyajha05@gmail.com?subject=Questions/Concerns" class="fa fa-envelope fa-2x"></a></li>
        <li><a href="#" class="fa fa-twitter fa-2x"></a></li>
      </ul>
  </section>


</body>

</html>

flaskblog/templates/blog.html
{% extends "layout.html" %}
{% block content %}
    <h1>Blog</h1>
    <br>
    {% for post in posts.items %}
        <article class="media blog-section">
          <div class="media-body">
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <div class="article-metadata">
              <small class="dates">{{ post.date_posted.strftime("%a, %d %b %Y") }} at {{ post.date_posted.strftime("%I:%M %p") }}</small>
            </div>
            <div id="module" class="container">
            <p class="collapse blog-content" id="contentCollapse" aria-expanded="false">
              {{ post.content }}
            </p>
            <a class="btn btn-sm btn-primary" href="{{ url_for('posts.post', post_id=post.id) }}" style="color: white">Read More</a>
            <hr>
          </div>
          </div>
        </article>

    {% endfor %}
        
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline mb-4" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flaskblog/templates/faqs.html
{% extends "layout.html" %}
{% block content %}
  	<h1>Some FAQ's</h1>
  	<p>If you have any other queries or concerns, feel free to email me at <a style="color: #007bff"href="mailto:achintyajha05@gmail.com?subject=Questions/Concerns">achintyajha05@gmail.com</a></p>

	<article class="media blog-section">
    	<div class="media-body">
        	<h2><span class="article-title">How did you create this website?</span></h2>
            <div id="module" class="container">
            <p>
              The frontend was made using HTML, CSS and a tiny bit of javascript (typical website stuff) , and for the backend I used Flask, a micro-framework for web-development in Python.
            </p>
            <hr>
          </div>
        </div>
    </article>

 
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
  <h1>About Me</h1>
  <img class="image-me img-fluid" style="width: 131px; padding: 15px; padding-left: 0px;" src="{{ url_for('static', filename='img/' + 'AchintyaPic.jpeg') }}"/>
  <p>
        Hey, I am a high school senior at Ahlcon International School. I have
        been a STEM enthusiast throughout high school, and not so
        surprisingly, I plan to major in Physics and Computer Science. Python
        is my thing folks; and as you might have figured, HTML isnt.

        <p>
        I am interested in Machine Learning and Data Science, and I have made some cool projects that you can check out at my <a href="https://github.com/achintya5">Github profile</a>. I have been using python for more than 3 years now, and I am proficient in major libraries such as Pytorch, Pandas, Numpy, Open-CV, and many more. Check out more about my programming journey and experience <a href="{{ url_for('main.programming') }}">here.</a>
        </p>
        Apart from academics, I have been interested in quite a few fields
        throughout my school years- prominently Taekwondo, music, and writing. 
        <br>
        Next up for you is what I like to call- 
        <br>
        Four years of
      <a href="{{ url_for('main.highschool') }}"> High School </a>
      in 5 minutes.
      <br>
      <p>
        I also have a
        <a href="https://www.youtube.com/watch?v=Y3K-XDYvTuc"
          >Youtube channel</a
        >
        where I upload guitar-cover videos, and occasionally, some Taekwondo
        tutorials.
      </p>
      <p>
        Contact me at- <a href="mailto:achintyajha05@gmail.com?subject=Questions/Concerns" style="color: #007bff">achintyajha05@gmail.com</a>.
      </p>
  </p>
{% endblock content %}

flaskblog/templates/hs.html
{% extends "layout.html" %}
{% block content %}

	<h1>High School</h1>
	<div>
      <img class="image-me img-fluid" style="width: 131px; padding: 15px; padding-left: 0px;" src="{{ url_for('static', filename='img/' + 'AchintyaPic.jpeg') }}"/>
    </div>
	<p>High school, the captain of my ship! High school has been an enriching experience. 
                I am a student at Ahlcon International School, where I have successfully involved 
                myself in many activities. From organising major in-school events to participating in 
                competitions, this has truly been an odyssey of the mind(intended).
                <br>
                Throughout this journey, 
                here's a bunch of cool stuff I did (and still doing).

    </p><br>
	<div class="list-group">
	  <a class="list-group-item list-group-item-action flex-column align-items-start">
	    <div class="d-flex w-100 justify-content-between">
	      <h5 class="mb-1">NASA Space Apps Challenge</h5>
	      <small class="text-muted">2020</small>
	    </div>
	    <p class="mb-1">National Winner</p>
	    <small class="text-muted">Our team created a website for increasing space awareness by using interactive stories and providing a digital & historical perspective on primitive as well as scientific research on greenhouse and glaciation period. </small>
	  </a>
	  <a class="list-group-item list-group-item-action flex-column align-items-start">
	    <div class="d-flex w-100 justify-content-between">
	      <h5 class="mb-1">Sakura Science Program</h5>
	      <small class="text-muted">2020</small>
	    </div>
	    <p class="mb-1">Indian Delegation</p>
	    <small class="text-muted">Part of the Indian delegation. Took part in the robotics camp and made an autonomous car with distance sensing and object detection.</small>
	  </a>
	  <a class="list-group-item list-group-item-action flex-column align-items-start">
	    <div class="d-flex w-100 justify-content-between">
	      <h5 class="mb-1">Odyssey of the Mind</h5>
	      <small class="text-muted">2015</small>
	    </div>
	    <p class="mb-1">First Place at the Nationals</p>
	    <small class="text-muted">Our team won the gold medal at the nationals in the Communication Skills category.</small>
	  </a>
	  <a class="list-group-item list-group-item-action flex-column align-items-start">
	    <div class="d-flex w-100 justify-content-between">
	      <h5 class="mb-1">Zenonco.io and Love Heals Cancer</h5>
	      <small class="text-muted">2020</small>
	    </div>
	    <p class="mb-1">Writer, Video Editor & Healing Circle Member</p>
	    <small class="text-muted">Did a 3-week internship at Zenonco and Love Heals Cancer, as a content-writer and film-maker.</small>
	  </a>
	  <a class="list-group-item list-group-item-action flex-column align-items-start">
	    <div class="d-flex w-100 justify-content-between">
	      <h5 class="mb-1">Taekwondo</h5>
	      <small class="text-muted">2014-Present</small>
	    </div>
	    <p class="mb-1">Black Belt Dan 1 and State Medallist</p>
	    <small class="text-muted">I have been doing Taekwondo for around 8 years now and throughout this period I have won three medals at State Championships and have played at the Nationals as well.</small>
	  </a>
	  <a class="list-group-item list-group-item-action flex-column align-items-start">
	    <div class="d-flex w-100 justify-content-between">
	      <h5 class="mb-1">Music & Guitar</h5>
	      <small class="text-muted">2015-Present</small>
	    </div>
	    <p class="mb-1">Trinity exams and School Band</p>
	    <small class="text-muted">I am a part of the school band, and we have performed several times for our school. I have also been taking Trinity graded exams in Rock and Pop Guitar.</small>
	  </a>
	  <a class="list-group-item list-group-item-action flex-column align-items-start">
	    <div class="d-flex w-100 justify-content-between">
	      <h5 class="mb-1">Video Editing-Film making-TV Production-Photography-Photoshop.
    	</h5>
	      <small class="text-muted">2018-Present</small>
	    </div>
	    <p class="mb-1">Internships and Projects</p>
	    <small class="text-muted">I was an intern at Myth Media, where I learned video editing, Photoshop, film-making and the state-of-the-art in this industry.</small>
	  </a>
	  <a class="list-group-item list-group-item-action flex-column align-items-start">
	    <div class="d-flex w-100 justify-content-between">
	      <h5 class="mb-1">MUNs/Debates and everything public speaking</h5>
	      <small class="text-muted">2016-Present</small>
	    </div>
	    <p class="mb-1">School and Individual Delegations</p>
	    <small class="text-muted">I have been an active participant in MUNs and debates. I have represented my school for the same and have won the Best Delegate award and many Honourable Mentions as well.</small>
	  </a>
	</div>
	<br>
	<br>
{% endblock content %}

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media">
    <div class="media-body">
      <h2 class="article-title">{{ post.title }}</h2>
      <div class="article-metadata">
        <small class="dates">{{ post.date_posted.strftime("%a, %d %b %Y") }} at {{ post.date_posted.strftime("%I:%M %p") }}</small>
      </div>
      {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Edit</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
    </div>
  </article>
  <br>
  <p class="article-content">{{ post.content }}</p>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2 style="font-family: 'Jost', sans-serif; font-size:25px"><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <div id="module" class="container">
            <p class="collapse" id="contentCollapse" aria-expanded="false">
              {{ post.content }}
            </p>
            <a class="btn btn-sm btn-primary" href="{{ url_for('posts.post', post_id=post.id) }}" style="color: white">Read More</a>
          </div>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}